DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS SECURITY_TEST;
DROP TABLE IF EXISTS TEST_STATUS;
DROP TABLE IF EXISTS FINDING;

CREATE TABLE IF NOT EXISTS PROJECT (
    ID         VARCHAR(36) NOT NULL,
    CLIENT     VARCHAR(255) NOT NULL,
    TITLE      VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME,
    -- DETAILS
    TESTER_NAME VARCHAR(255),
    SELECTED_LOGO_TESTER INT,
    SELECTED_LOGO_CLIENT INT,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SECURITY_TEST (
    ID VARCHAR(32) NOT NULL,
    CATEGORY VARCHAR(255),
    TITLE VARCHAR(255),
    DESCRIPTION TEXT,
    LINK VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TEST_STATUS (
    ID VARCHAR(36) NOT NULL,
    TEST_ID VARCHAR(255) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    TEST_PROGRESS VARCHAR(255) NOT NULL,
    CREATED DATETIME,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS FINDING (
    ID VARCHAR(36) NOT NULL,
    TEST_ID VARCHAR(255) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255),
    SEVERITY INTEGER,
    DESCRIPTION TEXT,
    REPRODUCTION TEXT,
    IMPACT TEXT,
    MITIGATION TEXT,
    AFFECTED_URLS TEXT,
    CREATED DATETIME,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SECURITY_TEST_PERFORMED (
    ID VARCHAR(255) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    TEST_ID VARCHAR(255) NOT NULL,
    CHECKED BOOLEAN(1) NOT NULL,
    COMMENT TEXT,
    PRIMARY KEY (ID)
);

-- TODO: Why does this only work here and not in test-data.sql?
INSERT INTO PROJECT VALUES('c02d0059-326f-4013-a2b1-0954e308bd00', 'E Corp', 'Some Mock API (v1.3) Scanning', parsedatetime('13-12-2018 17:04:18', 'dd-MM-yyyy hh:mm:ss'), 'NovaTester', 1, 2);
